<?php
$config=array(
	"title"=>"论坛",//模块名称
	"module"=>"forum",//模块目录
 	"version"=>1.2,//当前版本
	"info"=>"社区论坛",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"moduleadmin.php?m=forum&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>