<?php
$config=array(
	"title"=>"视频直播",//模块名称
	"module"=>"zblive",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"视频小直播",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=zblive&a=menu",
	"check_update"=>"http://www.skymvc.com",
);
?>