<?php
$config=array(
	"title"=>"B2C商城",//模块名称
	"module"=>"b2c",//模块目录
 	"version"=>1.1,//当前版本
	"info"=>"B2C商城是一款简单的在线商城系统，可以搭建外卖和普通的网上商城",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"moduleadmin.php?m=b2c&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>